### ISSUE TITLE
Create support?

### ISSUE THREAD

**Issue by mikaba-eu** [null2264/CobbleGen#16] opened 2023-04-13 12:46 UTC
I am not so familiar with minecraft mod development, but is it possible that to inject the rules to the create mod, if available?

Create have a own logic to create cobblestone, then you use a pipe:

https://github.com/Creators-of-Create/Create/blob/a92855254c9a7b85ba28781e2e3ce7169549cbf7/src/main/java/com/simibubi/create/content/contraptions/fluids/FluidReactions.java

**Comment by null2264** [comment] 2023-04-18 00:40
The fluid interaction is related to Create pipes? Looking at the code, it should be possible. I'll look into it later today.

**Comment by mikaba-eu** [comment] 2023-04-23 01:51
Wow thx! Will test this tomorrow! Thx!

**Comment by mikaba-eu** [comment] 2023-04-23 02:05
Can you upload a finished jar file for that? I don't have the environment here to compile java code.
After your upload, I test the new feature.

**Comment by null2264** [comment] 2023-04-23 02:10
Sure, I was waiting for it to compile.

[cobblegen.zip](https://github.com/null2264/CobbleGen/files/11302669/cobblegen.zip)

**Comment by mikaba-eu** [comment] 2023-04-23 02:33
thx. for some reason the whole mod dont work anymore? did you chance the way how to config it or something? I did not test the pipes from create now, but even the normal cobble gen only generate cobble now ...

And I get a few warnings in the console:
```
[04:13:23] [ForkJoinPool-1-worker-2/WARN]: Mod cobblegen uses the version v3.0b124-BETA which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:13:23] [ForkJoinPool-1-worker-2/WARN]: Mod cobblegen-1_19_3-compat uses the version v3.0b124-BETA which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:13:23] [ForkJoinPool-1-worker-8/WARN]: Mod xercapaint uses the version fabric-1.18.2-1.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:13:23] [ForkJoinPool-1-worker-2/WARN]: Mod cobblegen-1_19_2-compat uses the version v3.0b124-BETA which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:13:23] [ForkJoinPool-1-worker-2/WARN]: Mod cobblegen-1_18_2-compat uses the version v3.0b124-BETA which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
```

btw I play the create astral modpack.
MC: 1.18.2
Fabric: 0.14.14

**Comment by mikaba-eu** [comment] 2023-04-23 02:48
ok the create pipes seems to work! but not with regular lava.

https://cdn.discordapp.com/attachments/813762487253860376/1099527050949304424/2023-04-23_04-46-35.mp4

**Comment by null2264** [comment] 2023-04-23 03:06
Interesting... I'll troubleshoot it later today...

> And I get a few warnings in the console

Those are harmless, it's caused by my versioning scheme and should be fixed on the newest commit.

**Comment by null2264** [comment] 2023-04-23 03:54
After taking a quick look at create support commits, I think the problem is that I accidentally disabled the other mixins, which disabled the regular cobblestone generator function (it's supposed to only disable create support when create mod is not loaded, whoops)...

[cobblegen.zip](https://github.com/null2264/CobbleGen/files/11302813/cobblegen.zip)

**Closed as completed** 2023-04-23 09:22 UTC
Labels: enhancement

**Comment by mikaba-eu** [comment] 2023-04-23 14:34
seems so work well! Thank you very much.

**Comment by mikaba-eu** [comment] 2023-04-23 22:54
found a issue, I dont know if that is now create specific or from your mod.
normaly the lava source don't get consumed with create cobblestone generator. But then I use a basalt generator, the lava source get consumed =/

**Comment by null2264** [comment] 2023-04-24 00:59
I'm not familiar with Create Pipe fluid interactions but I think it's a normal Create behaviour. For Create cobblegen the flowing water transformed into cobblestone before any fluid gets used (flow?), but for basaltgen to work it needs to "spill" first, so the lava moved to the other side of the pipe and then transformed into basalt, hence consuming the lava. (It's just my guess tho, I never work with Create Pipes before)
